export default [
	{
		id: 3,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "add",
		title: "[FE] 드래그 앤 드랍 기능 구현",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 1,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "remove",
		title: "[BE] bugfix Json 구조 변경",
		fromColumn: "In Progress",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 2,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "update",
		title: "[BE] JWT 이용한 인증 기능 구현",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 1,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "add",
		title: "[FE] 카드 삭제 기능 구현",
		fromColumn: "In Progress",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 5,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "update",
		title: "[BE] bugfix Json 구조 변경",
		fromColumn: "Todo",
		toColumn: "In Progress",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 9,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "move",
		title: "Hey",
		fromColumn: "Todo",
		toColumn: "In Progress",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 2,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "move",
		title: "ViewModel로 로직 처리 변경 및 네트워크 처리",
		fromColumn: "In Progress",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 2,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "update",
		title: "[BE] JWT 이용한 인증 기능 구현",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 1,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "add",
		title: "[BE] bugfix Json 구조 변경",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 4,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "remove",
		title: "ViewModel로 로직 처리 변경 및 네트워크 처리",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
	{
		id: 4,
		userId: "sunny",
		profileURL: "https://www.guitartabsexplorer.com/images/tabs/colde_please_love_me.jpg",
		action: "remove",
		title: "ViewModel로 로직 처리 변경 및 네트워크 처리",
		fromColumn: "Todo",
		toColumn: "Done",
		actionTime: "2020-04-11 20:48:38",
	},
];
